### ISSUE TITLE
404 Not Found Error

### ISSUE THREAD

**Issue by MuizU** [entitize/Fakeddit#11]
I get an  error like the one below after I run ` python image_downloader.py all_train.tsv` from the all_samples folder 

`  0%|                                                                           | 2/878218 [00:04<544:15:53,  2.23s/it]Traceback (most recent call last):                                                                                         File "image_downloader.py", line 26, in <module>                                                                          urllib.request.urlretrieve(image_url, "images/" + row["id"] + ".jpg")                                                 File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 247, in urlretrieve                                                                                             with contextlib.closing(urlopen(url, data)) as fp:                                                                    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 222, in urlopen                                                                                                 return opener.open(url, data, timeout)                                                                                File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 531, in open                                                                                                    response = meth(req, response)                                                                                        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 640, in http_response                                                                                           response = self.parent.error(                                                                                         File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 569, in error                                                                                                   return self._call_chain(*args)                                                                                        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 502, in _call_chain                                                                                             result = func(*args)                                                                                                  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 649, in http_error_default                                                                                      raise HTTPError(req.full_url, code, msg, hdrs, fp)                                                                  urllib.error.HTTPError: HTTP Error 404: Not Found     `

**Comment by entitize** [comment]
Please try downloading the images from google drive link on the README directly. If that doesn't work try: https://drive.google.com/drive/folders/1vNFLeuf8__lJLSGdpq1TyMeOLSUWv_BD
