### ISSUE TITLE
are the result in your paper correct?

### ISSUE THREAD

**Issue by serryuer** [entitize/Fakeddit#2]
I used pretrainde BERT(uncased_L-24_H-1024_A-16) to do the 2-way classification task, the result were different with your paper, I got (0.87 accuracy score/0.86 f1 score) in validate data, the result in test data is similar, so can you give me some advices?

**Comment by cococold** [comment]
> I used pretrainde BERT(uncased_L-24_H-1024_A-16) to do the 2-way classification task, the result were different with your paper, I got (0.87 accuracy score/0.86 f1 score) in validate data, the result in test data is similar, so can you give me some advices?

I got a similar result for the classification based on the ''clean_title'' field. However, I still want to evaluate the performance on the private test set (leadboard).

**Comment by entitize** [comment]
Apologies for the late response. We have updated the dataset and paper.
