### ISSUE TITLE
The images are hard to access.

### ISSUE THREAD

**Issue by cococold** [entitize/Fakeddit#3]
Hi, I am working on crawling the images using the script you provided, but I found it's very slow and lots of image_url is invalid. So is it convenient for you to pack all of the images and public it?

**Comment by entitize** [comment]
The entire image dataset is over 100GB. Do you have any suggestions on how to upload them so it's more convenient for you to download?

**Comment by Meywether** [comment]
Dear entitize, thanks for providing such a huge dataset for fake detection.
I can sugget: [transferxl](https://transferxl.com/)
Thanks in advance!

**Comment by entitize** [comment]
We have added a google drive link to the dataset images in the README
