### ISSUE TITLE
[Bug]? - Mismatch between column num_comments and real comments

### ISSUE THREAD

**Issue by Meywether** [entitize/Fakeddit#6]
Dear entitize, 

I recognized around 80k mismatches in the column num_comments and real comments, found in all_comments.tsv. Sometimes there are less real comments than mentioned and sometimes more. I attached a file, maybe it can help you: [mismatchingComments.txt](https://github.com/entitize/Fakeddit/files/4670064/mismatchingComments.txt)

Update: This file only contains the mismatching entries within the train set!

Best regards
Meywether

**Comment by entitize** [comment]
Hi Meywether,

The difference may have resulted from the fact that comments may have been added or deleted after dataset was created.
